# Generated by Django 4.2.23 on 2025-06-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0002_alter_category_type_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
